services:
  qe:
    build: .
    container_name: qe
    user: "1000:1000"
    environment:
      OMP_NUM_THREADS: 1
      QE_ROOT: /opt/qe-7.6
      ESPRESSO_PSEUDO: /opt/qe-7.6/pseudo
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      OMPI_MCA_hwloc_base_binding_policy: none
    volumes:
      - qe_home:/home/qe
      - ./jobs_qe:/home/qe/jobs_qe
    ulimits:
      stack: -1
    shm_size: "2gb"
    restart: unless-stopped

volumes:
  qe_home:
